import type { Metadata } from "next";
import { ArrowUpRight, Blocks, BrainCircuit, CloudCog, CodeXml, DraftingCompass, PlugZap } from "lucide-react";
import { CtaBand, PageFrame, Reveal, SectionHeader } from "../site-ui";
export const metadata: Metadata = { title: "Services", description: "Techabanca works across product engineering, cloud systems, AI and automation, design, and integration." };
const services = [
  { id:"product-engineering", number:"01", icon:<CodeXml/>, title:"Product engineering", summary:"From first principles to production-ready software.", details:"Web applications, SaaS products, internal tools, and customer experiences designed for usefulness, maintainability, and growth.", tags:["WEB APPLICATIONS","SAAS PRODUCTS","FRONTEND ENGINEERING"] },
  { id:"ai-automation", number:"02", icon:<BrainCircuit/>, title:"AI & automation", summary:"Give people more room to do meaningful work.", details:"Practical AI-assisted experiences and workflow automation built around clear business outcomes and responsible human oversight.", tags:["WORKFLOW AUTOMATION","AI FEATURES","PROCESS DESIGN"] },
  { id:"cloud-engineering", number:"03", icon:<CloudCog/>, title:"Cloud engineering", summary:"Infrastructure that supports what comes next.", details:"Cloud-native foundations, deployment workflows, and application architecture planned for resilience and thoughtful scaling.", tags:["CLOUD ARCHITECTURE","DEPLOYMENT","RELIABILITY"] },
  { id:"experience-design", number:"04", icon:<DraftingCompass/>, title:"Experience design", summary:"Make sophisticated systems feel intuitive.", details:"Structure and interface design that clarify complex workflows and help people move with confidence.", tags:["UX STRATEGY","INTERFACE DESIGN","DESIGN SYSTEMS"] },
  { id:"integration", number:"05", icon:<PlugZap/>, title:"Systems integration", summary:"Let your tools work together.", details:"APIs and integrations that connect information across systems and reduce duplicated effort.", tags:["APIS","INTEGRATIONS","DATA FLOWS"] },
  { id:"consulting", number:"06", icon:<Blocks/>, title:"Technology consulting", summary:"Make better technical decisions early.", details:"Collaborative discovery and solution planning that align implementation choices with business needs.", tags:["DISCOVERY","ARCHITECTURE","ROADMAPS"] },
];
export default function Services() { return <PageFrame><main><section className="interior-hero services-hero"><div className="container"><p className="eyebrow"><span className="signal"/> CAPABILITIES / 01—06</p><h1>Technology that<br/><em>works harder.</em></h1><p className="interior-lead">From a focused digital product to an interconnected platform, our work starts with understanding what needs to change.</p><a href="#services" className="button button-primary">Explore capabilities <ArrowUpRight size={18}/></a></div></section><section id="services" className="section-pad"><div className="container"><Reveal><SectionHeader index="01 / CAPABILITIES" title={<>Ideas made <span>operational.</span></>} description="A considered mix of strategy, design, and engineering. Explore where we can contribute."/></Reveal><div className="service-list">{services.map(s=><Reveal key={s.id}><article id={s.id} className="service-detail"><div className="service-no">{s.number} / 06</div><div className="service-main"><div className="service-icon">{s.icon}</div><h2>{s.title}</h2><h3>{s.summary}</h3><p>{s.details}</p><div className="tag-list">{s.tags.map(t=><span key={t}>{t}</span>)}</div></div><ArrowUpRight className="service-arrow"/></article></Reveal>)}</div></div></section><section className="section-pad service-method"><div className="container"><Reveal><SectionHeader index="02 / WORKING TOGETHER" title={<>A straightforward way <span>to make progress.</span></>} description="Good work starts with shared understanding and stays open to learning along the way."/></Reveal><div className="method-grid">{[["01","DISCOVER","Understand the challenge, constraints, and people involved."],["02","SHAPE","Define a practical direction and the right scope."],["03","BUILD","Deliver in focused steps with care for quality."],["04","EVOLVE","Learn from real use and improve what matters."]].map(m=><div key={m[0]}><span>{m[0]}</span><h3>{m[1]}</h3><p>{m[2]}</p></div>)}</div></div></section><CtaBand/></main></PageFrame>; }
