import type { Metadata } from "next";
import { ArrowUpRight, Blocks, BriefcaseBusiness, Factory, Store } from "lucide-react";
import { CtaBand, PageFrame, Reveal, SectionHeader } from "../site-ui";
import { SolutionExplorer } from "./solution-explorer";

export const metadata: Metadata = { title: "Solutions", description: "Explore how Techabanca approaches connected systems for commerce, professional services, and growing operations." };

export default function Solutions() { return <PageFrame><main>
  <section className="interior-hero solutions-hero"><div className="container solutions-hero-grid"><div><p className="eyebrow"><span className="signal"/> CONTEXT CHANGES EVERYTHING</p><h1>Built around<br/><em>your reality.</em></h1><p className="interior-lead">Every business has its own constraints, workflows, and opportunities. We start with the way your teams work, then design technology around it.</p><a href="#explore-solutions" className="button button-primary">Explore solutions <ArrowUpRight size={18}/></a></div><div className="solutions-network" role="img" aria-label="A connected flow from business information through workflows to clearer decisions"><span className="network-label">CONNECTED SYSTEMS / 01</span><div className="network-row network-input"><span>PRODUCTS</span><span>CUSTOMERS</span><span>TEAMS</span></div><div className="network-junction">↓ &nbsp; ↓ &nbsp; ↓</div><div className="network-center"><Blocks size={28}/><strong>BETTER WORKFLOWS</strong><small>DESIGNED AROUND PEOPLE</small></div><div className="network-junction">↓</div><div className="network-row network-output"><span>CLARITY</span><span>PROGRESS</span></div></div></div></section>
  <section className="section-pad solutions-intro"><div className="container"><Reveal><SectionHeader index="01 / AREAS OF FOCUS" title={<>Different worlds. <span>Shared ambition.</span></>} description="An approach to useful technology across the operations that keep businesses moving."/></Reveal><div className="solutions-grid"><a href="#commerce" className="solution-card"><Store/><span>01 / COMMERCE</span><h3>Retail & distribution</h3><p>Connect product, customer, and document flows.</p><ArrowUpRight className="solution-arrow"/></a><a href="#services" className="solution-card"><BriefcaseBusiness/><span>02 / SERVICES</span><h3>Professional services</h3><p>Give teams clarity across the work they deliver.</p><ArrowUpRight className="solution-arrow"/></a><a href="#operations" className="solution-card"><Factory/><span>03 / OPERATIONS</span><h3>Growing businesses</h3><p>Replace fragmented processes with better systems.</p><ArrowUpRight className="solution-arrow"/></a></div></div></section>
  <section className="section-pad solutions-explorer" id="explore-solutions"><div className="container"><Reveal><SectionHeader index="02 / EXPLORE THE WORK" title={<>From friction to <span>flow.</span></>} description="Explore possible starting points for a more connected business. Every engagement begins with discovery."/></Reveal><SolutionExplorer/></div></section>
  <section className="section-pad solutions-bridge"><div className="container bridge-grid"><Reveal><div><span className="mini-label">PRODUCT + PRACTICE</span><h2 className="display-heading">Starting with <span>Billing.</span><br/>Thinking beyond it.</h2></div></Reveal><Reveal><div><p className="lead-copy">Techabanca Billing addresses a familiar business need. Our broader engineering practice is for the workflows and systems unique to your organization.</p><div className="bridge-links"><a href="/billing">Explore Billing <ArrowUpRight size={18}/></a><a href="/services">Explore services <ArrowUpRight size={18}/></a></div></div></Reveal></div></section>
  <CtaBand/>
</main></PageFrame>; }
