import type { Metadata } from "next";
import { ArrowUpRight, ChartNoAxesCombined, Globe, Images, Layers3, MessagesSquare, SlidersHorizontal } from "lucide-react";
import { PageFrame, Reveal, SectionHeader } from "../site-ui";
import { catalogueProduct } from "../product-catalog";
import { CatalogueScreen } from "./catalogue-screen";
import { CatalogueTour } from "./product-tour";

export const metadata: Metadata = {
  title: "Catalogue — A better showcase for your business",
  description: "Explore Techabanca Catalogue: organize products and services, maintain item details and imagery, prepare your catalogue website, and manage enquiries in one responsive workspace.",
  alternates: { canonical: "https://techabanca.com/catalogue/" },
  openGraph: { title: "Techabanca Catalogue — A better showcase for your business", description: "Products, services, website content and customer enquiries in one considered workspace. Explore the real application and current early-access availability.", url: "https://techabanca.com/catalogue/", type: "website", images: [{ url: "https://techabanca.com/images/catalogue/example-industries/published.jpg", width: 1440, height: 960, alt: "Published Example Industries website created with Techabanca Catalogue" }] },
};
const features = [
  { icon: Layers3, title: "Products and services", text: "One place for physical products, professional services, or a business that offers both. Categories keep the range easy to navigate." },
  { icon: SlidersHorizontal, title: "Details that fit your business", text: "Go beyond an item name. Maintain descriptions, SKUs, optional prices, and custom specifications that explain your offer." },
  { icon: Images, title: "Imagery with a purpose", text: "Keep product galleries, supported item documents and business images close to the content they help explain." },
  { icon: Globe, title: "A considered website workflow", text: "Maintain website content and prepare private previews. Saved content and published revisions stay separate; public activation is being finalized." },
  { icon: MessagesSquare, title: "A home for enquiries", text: "Use the dedicated enquiry workspace to review conversations, track New, Contacted and Closed statuses, and keep team notes." },
  { icon: ChartNoAxesCombined, title: "Business context and visibility", text: "Maintain your business profile and contacts. Explore catalogue activity and sharing tools when your public website is active." },
];
const uses = [
  ["01 / RETAIL & DISTRIBUTION", "Make your range easier to explore.", "Keep products, categories and specifications together, with imagery and details that help explain the choices."],
  ["02 / PROFESSIONAL SERVICES", "Give your expertise a clear shape.", "Describe your services, deliverables and business-specific details so people can understand what you offer."],
  ["03 / STUDIOS & MAKERS", "Let the details tell the story.", "Bring materials, craft, custom work and visual context into a consistent catalogue you can continue to refine."],
];
const faqs = [
  ["What is Techabanca Catalogue?", "A separate web application for organizing your products and services, preparing a catalogue website, and managing customer enquiries. It brings business information, item content and website controls into one workspace."],
  ["Can I catalogue services as well as products?", "Yes. Choose products, services, or both during business setup. Organize the items into categories and add fields that fit your business."],
  ["Do I need to design a website from scratch?", "No. Catalogue includes a managed professional theme and guided setup. You prepare business information, imagery and content, then use the preview and publication workflow subject to its availability."],
  ["What is available in early access?", "Account creation and workspace setup are available, and the published Example Industries pilot can be explored on this page. Wider public website activation is being finalized. Creating an account does not publish a website, start a trial, or activate a paid subscription."],
  ["How much does it cost?", "Creating your workspace requires no payment method. Eligible owners and admins can explicitly start the optional 14-day trial from Subscription, with no card or automatic paid renewal. Paid plans and their prices are not available yet; check the application’s Pricing area for current availability."],
  ["Can I work from my phone?", "Yes. Catalogue adapts to desktop and mobile browsers. Use the same Catalogue account and workspace; there is no separate app to install."],
  ["How does it fit alongside Techabanca Billing?", "Billing focuses on sales documents, purchases, expenses and business reports. Catalogue focuses on presenting your offer and managing its content. Each application has its own workspace; automatic synchronization of records between the two is not currently offered."],
];
export default function CataloguePage() {
  return <PageFrame><main className="catalogue-page" id="catalogue-main">
    <section className="interior-hero catalogue-hero" aria-labelledby="catalogue-title"><div className="container catalogue-hero-grid">
      <div><p className="eyebrow"><span className="signal" /> TECHABANCA CATALOGUE / EARLY ACCESS</p><h1 id="catalogue-title">Your offer.<br /><em>A better showcase.</em></h1><p className="interior-lead">Make what you do easy to explore. Bring products, services, website content and customer enquiries into a workspace shaped around your business.</p><div className="hero-actions"><a className="button button-primary" href={catalogueProduct.appHref} target="_blank" rel="noreferrer">Explore the application <ArrowUpRight size={18} /></a><a className="button button-text" href="#inside-catalogue">Take the product tour <ArrowUpRight size={18} /></a></div><p className="catalogue-hero-note">Early access · Workspace setup is available.<br />Explore the live Example Industries example.<br />Wider public activation is being finalized.</p></div>
      <div className="catalogue-hero-visual"><CatalogueScreen file="published" label="EXAMPLE INDUSTRIES / PUBLISHED WEBSITE" alt="Example Industries live catalogue website showing business navigation and the LED TV product, captured from the production domain" eager /><div className="catalogue-hero-label"><span aria-hidden="true">↗</span><div><strong>Your business, in focus.</strong><span>Products. Services. The details that matter.</span></div></div></div>
    </div></section>
    <nav className="catalogue-jumpnav" aria-label="Catalogue page sections"><div className="container"><a href="#inside-catalogue">Inside the product <span>01</span></a><a href="#catalogue-features">Capabilities <span>02</span></a><a href="#catalogue-workflow">Your workflow <span>03</span></a><a href="#catalogue-availability">Pricing & availability <span>04</span></a></div></nav>
    <section className="section-pad catalogue-light" id="inside-catalogue"><div className="container"><Reveal><SectionHeader index="01 / TAKE A CLOSER LOOK" title={<>Real screens. <span>Useful possibilities.</span></>} description="Follow Example Industries from its production workspace to its published website. These are the same account and live website captures used by Techabanca Catalogue." /></Reveal><CatalogueTour /></div></section>
    <section className="section-pad catalogue-usecases"><div className="container"><Reveal><SectionHeader index="MADE FOR THE WAY YOU OFFER" title={<>Different businesses. <span>A clearer presentation.</span></>} description="Start with the way your business works, then shape the catalogue around what customers need to understand." /></Reveal><div className="catalogue-use-grid">{uses.map(([label,title,text]) => <Reveal key={label}><article><span>{label}</span><h3>{title}</h3><p>{text}</p></article></Reveal>)}</div></div></section>
    <section className="section-pad catalogue-features" id="catalogue-features"><div className="container"><Reveal><SectionHeader index="02 / THE ESSENTIALS, CONNECTED" title={<>More than a list. <span>A working catalogue.</span></>} description="Maintain the content behind your offer, with room for the website and next customer conversation." /></Reveal><div className="catalogue-feature-grid">{features.map(({icon:Icon,title,text},index) => <Reveal key={title}><article><div><span>0{index+1} / 06</span><Icon size={25} aria-hidden="true" /></div><h3>{title}</h3><p>{text}</p></article></Reveal>)}</div></div></section>
    <section className="section-pad catalogue-workflow" id="catalogue-workflow"><div className="container catalogue-workflow-grid"><Reveal><div><p className="section-kicker">03 / FROM CONTENT TO CONVERSATION</p><h2 className="display-heading">Build the details.<br /><span>Prepare the next step.</span></h2><p className="lead-copy">A guided start and a considered publishing workflow help you shape your catalogue at your own pace.</p><a className="inline-link" href={catalogueProduct.appHref + "#signup"} target="_blank" rel="noreferrer">Create your workspace <ArrowUpRight size={18} /></a></div></Reveal><Reveal><ol>{[["Set up your business", "Choose products, services, or both. Add your business identity and the information people need to know."],["Give your offer its context", "Create categories and items, add imagery and details, and refine the content that makes your offer useful."],["Review before you share", "Prepare a private preview and review the revision you intend to publish. Public activation is a separate step and is being finalized for launch."]].map(([title,text],index)=><li key={title}><span>0{index+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></Reveal></div></section>
    <section className="section-pad catalogue-detail"><div className="container catalogue-detail-grid"><CatalogueScreen file="item" label="ITEM DETAILS / EXAMPLE INDUSTRIES" alt="Example Industries LED TV editor showing the SKU, item descriptions, custom fields and configured price in the production account" /><Reveal><div><p className="section-kicker">DETAILS THAT DO THE TALKING</p><h2 className="display-heading">Give every item<br /><span>a better introduction.</span></h2><p className="lead-copy">A name gets attention. Good context helps someone understand. Keep descriptions, specifications, categories and optional prices in one place.</p><ul className="catalogue-checklist"><li>Business-specific fields and specifications</li><li>Products and services in the same catalogue</li><li>Images and supported item documents</li><li>Draft, hidden and featured item controls</li></ul></div></Reveal></div></section>
    <section className="section-pad catalogue-mobile"><div className="container catalogue-mobile-grid"><Reveal><div><p className="section-kicker">YOUR BUSINESS, WITH YOU</p><h2 className="display-heading">A full workspace.<br /><span>A smaller screen.</span></h2><p className="lead-copy">Review your catalogue at the desk or pick up where you left off on your phone. The responsive workspace adapts to the browser you already use.</p><div className="catalogue-mobile-proof"><span>Same Catalogue account</span><span>No app to install</span></div><a className="inline-link" href={catalogueProduct.appHref} target="_blank" rel="noreferrer">Open Catalogue <ArrowUpRight size={18} /></a></div></Reveal><div className="catalogue-device-pair"><CatalogueScreen file="workspace" label="EXAMPLE INDUSTRIES / DESKTOP WORKSPACE" alt="Example Industries desktop workspace in the production Catalogue account" /><figure className="catalogue-phone"><div className="catalogue-phone-speaker" aria-hidden="true" /><img src="/images/catalogue/example-industries/mobile.jpg" alt="Example Industries production Catalogue account on a mobile browser with compact navigation" width={390} height={844} loading="lazy" decoding="async" /><figcaption>Example Industries · Mobile</figcaption></figure></div></div></section>
    <section className="section-pad catalogue-light" id="catalogue-availability"><div className="container"><Reveal><SectionHeader index="04 / A CLEAR START" title={<>Explore today. <span>Know what comes next.</span></>} description="Catalogue is in early access. Workspace setup, subscription access and public website activation are separate steps." /></Reveal><div className="catalogue-availability-grid"><article><span className="catalogue-status">AVAILABLE NOW</span><h3>Your workspace</h3><p className="catalogue-setup-price">₹0 <span>to create your workspace</span></p><p>Set up your business and organize your catalogue content. No payment method is required for account creation.</p><a className="button button-dark catalogue-dark-button" href={catalogueProduct.appHref+"#signup"} target="_blank" rel="noreferrer">Create your workspace <ArrowUpRight size={18} /></a></article><article><span className="catalogue-status catalogue-status-muted">COMING SOON</span><h3>Paid subscriptions</h3><p className="catalogue-paid-price">To be announced</p><p>Paid plans and checkout are not available yet. Public website activation is being finalized; account creation does not publish a website.</p><a className="catalogue-light-link" href={catalogueProduct.appHref+"#pricing"} target="_blank" rel="noreferrer">See current pricing & availability <ArrowUpRight size={18} /></a></article></div><div className="catalogue-trial-copy"><strong>Optional 14-day trial</strong><p>Eligible owners and admins can explicitly start the trial from Subscription. No card is required and there is no automatic paid renewal. Signup itself does not start the trial.</p></div></div></section>
    <section className="section-pad catalogue-faq" id="catalogue-questions"><div className="container catalogue-faq-grid"><Reveal><div><p className="section-kicker">A LITTLE CLARITY</p><h2 className="display-heading">Before you<br /><span>get started.</span></h2><p className="lead-copy">The product, the next step, and how it fits your business.</p></div></Reveal><div>{faqs.map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="catalogue-final"><div className="container"><div><p className="section-kicker">YOUR OFFER DESERVES A BETTER HOME.</p><h2>Show what you do.<br /><em>Make it worth exploring.</em></h2></div><div><a className="button catalogue-dark-button" href={catalogueProduct.appHref} target="_blank" rel="noreferrer">Discover Techabanca Catalogue <ArrowUpRight size={18} /></a><p>Explore the product and current early-access availability.</p></div></div></section>
  </main></PageFrame>;
}
